/* Icon set: Remix Icon, Fill variant, via @remixicon/react.
   Components are re-exported under semantic names so call sites stay stable
   if an icon is swapped later. Size via className (e.g. "size-5"). */
export {
  RiCheckFill as Check,
  RiSubtractFill as Minus,
  RiArrowLeftFill as ArrowLeft,
  RiStarFill as Star,
  RiArrowRightFill as ArrowRight,
  RiArrowRightUpFill as ArrowUpRight,
  RiShieldCheckFill as ShieldCheck,
  RiPaletteFill as Palette,
  RiPencilFill as PenLine,
  RiSpeedUpFill as Gauge,
  RiSearchFill as Search,
  RiLifebuoyFill as LifeBuoy,
  RiChat3Fill as MessageCircle,
  RiEyeFill as Eye,
  RiFlashlightFill as Zap,
  RiPriceTag3Fill as Tag,
  RiInstagramFill as Instagram,
  RiMailFill as Mail,
  RiGlobalLine as Globe,
  RiLinkedinFill as Linkedin,
  RiLayout4Fill as LayoutTemplate,
  RiShoppingBag3Fill as ShoppingBag,
  RiBuilding2Fill as Building,
  RiWindowFill as AppWindow,
  RiWhatsappLine as Whatsapp,
  RiArrowRightSLine as ChevronRight,
  RiSparkling2Fill as Sparkle,
  RiArrowUpLine as ArrowUp,
  RiMenuLine as Menu,
  RiCloseLine as Close,
  /* Line variants. The set is Fill by default, which suits small icons on dark grounds
     (the 16px shield in the hero). At 24px on a pale card the solid shapes read heavy,
     so the two secondary cards use these instead. */
  RiPencilLine as PenLineOutline,
  RiShieldCheckLine as ShieldCheckOutline,
} from "@remixicon/react";
